### ISSUE TITLE
HTML - Create Footer with the Contact Us Elements

### ISSUE THREAD

**Issue by DesislavaMetodieva** [heirfanahmed/mood-movies#12]
**User Story:**
As a client, when I click on the contact us pointer it takes to the GitHub repository.

**Acceptance Criteria:**
The contact us text should be displayed at the bottom of the web page.

The text is a normal text when hovered takes the client to the GitHub repository.

The contact us text should be responsive and adjust its layout on smaller screens.

**Comment by heirfanahmed** [comment]
All done drafting the document.
