### ISSUE TITLE
HTML - Create Form/Search Elements

### ISSUE THREAD

**Issue by DesislavaMetodieva** [heirfanahmed/mood-movies#13]
**User Story:**
As a client, I want to search for the location I require and the web app provides me with the weather report of my location.

**Acceptance Criteria:**
The search text should be displayed below the navigation bar on the website.

The search button should be in the centre of its div on the web page.

The search text and search button should be responsive and adjust its layout on smaller screens.

**Comment by heirfanahmed** [comment]
All done and looks great.
