### ISSUE TITLE
Create README file.

### ISSUE THREAD

**Issue by DesislavaMetodieva** [heirfanahmed/mood-movies#8]
**User Story:**

As a client, when I open the readme file, it shows me the Task, User Story, Acceptance Criteria, Description of the Project, Technologies Used, Screen shot of the deployed webpage, URLs of the repository and the deployed website.

**Acceptance Criteria:**
Once the README file is opened, it should be neat and clean drafted points on all the above mentioned headings.

It should have points (numbered or bullet points) when drafting Description of the Project, Technologies Used and Action.

It should have the URLs link to the repository and deployed website.

**Comment by heirfanahmed** [comment]
All done and only the screen shot of the deployed webpage and URLs of the repository & deployed webpage to be added once the project is completed.
